// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpgqvecblgvhtouclfqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwZ3F2ZWNibGd2aHRvdWNsZnFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MDMyMjAsImV4cCI6MjA2OTA3OTIyMH0.zTMyXcYaHOeJc5cQ-5Zot9s6Kcec4-iAZucSyEIieqw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});